name: Arachnie CI - Build & Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Trigger Vercel Deploy Hook
        if: success()
        run: |
            curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}

        # https://api.vercel.com/v1/integrations/deploy/prj_leTodw6bI3bTN37L7xTviJCtI78l/93DfG66lfl
